// Generated by gencpp from file global_planner/Frenet2WorldServiceResponse.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICERESPONSE_H
#define GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <global_planner/WorldPose.h>

namespace global_planner
{
template <class ContainerAllocator>
struct Frenet2WorldServiceResponse_
{
  typedef Frenet2WorldServiceResponse_<ContainerAllocator> Type;

  Frenet2WorldServiceResponse_()
    : world_pose()  {
    }
  Frenet2WorldServiceResponse_(const ContainerAllocator& _alloc)
    : world_pose(_alloc)  {
  (void)_alloc;
    }



   typedef  ::global_planner::WorldPose_<ContainerAllocator>  _world_pose_type;
  _world_pose_type world_pose;





  typedef boost::shared_ptr< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Frenet2WorldServiceResponse_

typedef ::global_planner::Frenet2WorldServiceResponse_<std::allocator<void> > Frenet2WorldServiceResponse;

typedef boost::shared_ptr< ::global_planner::Frenet2WorldServiceResponse > Frenet2WorldServiceResponsePtr;
typedef boost::shared_ptr< ::global_planner::Frenet2WorldServiceResponse const> Frenet2WorldServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator1> & lhs, const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.world_pose == rhs.world_pose;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator1> & lhs, const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace global_planner

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a89febe28dc7b8596bb180ba9404e6a5";
  }

  static const char* value(const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa89febe28dc7b859ULL;
  static const uint64_t static_value2 = 0x6bb180ba9404e6a5ULL;
};

template<class ContainerAllocator>
struct DataType< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "global_planner/Frenet2WorldServiceResponse";
  }

  static const char* value(const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "WorldPose world_pose\n"
"\n"
"================================================================================\n"
"MSG: global_planner/WorldPose\n"
"float64 x\n"
"float64 y\n"
"float64 yaw\n"
"float64 v\n"
"float64 acc\n"
"float64 target_v\n"
;
  }

  static const char* value(const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.world_pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Frenet2WorldServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::global_planner::Frenet2WorldServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "world_pose: ";
    s << std::endl;
    Printer< ::global_planner::WorldPose_<ContainerAllocator> >::stream(s, indent + "  ", v.world_pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICERESPONSE_H
