// Generated by gencpp from file global_planner/Frenet2WorldService.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICE_H
#define GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICE_H

#include <ros/service_traits.h>


#include <global_planner/Frenet2WorldServiceRequest.h>
#include <global_planner/Frenet2WorldServiceResponse.h>


namespace global_planner
{

struct Frenet2WorldService
{

typedef Frenet2WorldServiceRequest Request;
typedef Frenet2WorldServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Frenet2WorldService
} // namespace global_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::global_planner::Frenet2WorldService > {
  static const char* value()
  {
    return "7c3d04499a34679df3b3eaae1ccad4b8";
  }

  static const char* value(const ::global_planner::Frenet2WorldService&) { return value(); }
};

template<>
struct DataType< ::global_planner::Frenet2WorldService > {
  static const char* value()
  {
    return "global_planner/Frenet2WorldService";
  }

  static const char* value(const ::global_planner::Frenet2WorldService&) { return value(); }
};


// service_traits::MD5Sum< ::global_planner::Frenet2WorldServiceRequest> should match
// service_traits::MD5Sum< ::global_planner::Frenet2WorldService >
template<>
struct MD5Sum< ::global_planner::Frenet2WorldServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::global_planner::Frenet2WorldService >::value();
  }
  static const char* value(const ::global_planner::Frenet2WorldServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planner::Frenet2WorldServiceRequest> should match
// service_traits::DataType< ::global_planner::Frenet2WorldService >
template<>
struct DataType< ::global_planner::Frenet2WorldServiceRequest>
{
  static const char* value()
  {
    return DataType< ::global_planner::Frenet2WorldService >::value();
  }
  static const char* value(const ::global_planner::Frenet2WorldServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::global_planner::Frenet2WorldServiceResponse> should match
// service_traits::MD5Sum< ::global_planner::Frenet2WorldService >
template<>
struct MD5Sum< ::global_planner::Frenet2WorldServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::global_planner::Frenet2WorldService >::value();
  }
  static const char* value(const ::global_planner::Frenet2WorldServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planner::Frenet2WorldServiceResponse> should match
// service_traits::DataType< ::global_planner::Frenet2WorldService >
template<>
struct DataType< ::global_planner::Frenet2WorldServiceResponse>
{
  static const char* value()
  {
    return DataType< ::global_planner::Frenet2WorldService >::value();
  }
  static const char* value(const ::global_planner::Frenet2WorldServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GLOBAL_PLANNER_MESSAGE_FRENET2WORLDSERVICE_H
