// Generated by gencpp from file global_planner/World2FrenetService.msg
// DO NOT EDIT!


#ifndef GLOBAL_PLANNER_MESSAGE_WORLD2FRENETSERVICE_H
#define GLOBAL_PLANNER_MESSAGE_WORLD2FRENETSERVICE_H

#include <ros/service_traits.h>


#include <global_planner/World2FrenetServiceRequest.h>
#include <global_planner/World2FrenetServiceResponse.h>


namespace global_planner
{

struct World2FrenetService
{

typedef World2FrenetServiceRequest Request;
typedef World2FrenetServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct World2FrenetService
} // namespace global_planner


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::global_planner::World2FrenetService > {
  static const char* value()
  {
    return "530f2b7503e3482b362b155805927d68";
  }

  static const char* value(const ::global_planner::World2FrenetService&) { return value(); }
};

template<>
struct DataType< ::global_planner::World2FrenetService > {
  static const char* value()
  {
    return "global_planner/World2FrenetService";
  }

  static const char* value(const ::global_planner::World2FrenetService&) { return value(); }
};


// service_traits::MD5Sum< ::global_planner::World2FrenetServiceRequest> should match
// service_traits::MD5Sum< ::global_planner::World2FrenetService >
template<>
struct MD5Sum< ::global_planner::World2FrenetServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::global_planner::World2FrenetService >::value();
  }
  static const char* value(const ::global_planner::World2FrenetServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planner::World2FrenetServiceRequest> should match
// service_traits::DataType< ::global_planner::World2FrenetService >
template<>
struct DataType< ::global_planner::World2FrenetServiceRequest>
{
  static const char* value()
  {
    return DataType< ::global_planner::World2FrenetService >::value();
  }
  static const char* value(const ::global_planner::World2FrenetServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::global_planner::World2FrenetServiceResponse> should match
// service_traits::MD5Sum< ::global_planner::World2FrenetService >
template<>
struct MD5Sum< ::global_planner::World2FrenetServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::global_planner::World2FrenetService >::value();
  }
  static const char* value(const ::global_planner::World2FrenetServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::global_planner::World2FrenetServiceResponse> should match
// service_traits::DataType< ::global_planner::World2FrenetService >
template<>
struct DataType< ::global_planner::World2FrenetServiceResponse>
{
  static const char* value()
  {
    return DataType< ::global_planner::World2FrenetService >::value();
  }
  static const char* value(const ::global_planner::World2FrenetServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GLOBAL_PLANNER_MESSAGE_WORLD2FRENETSERVICE_H
